import './globals.css'
import { Providers } from './redux/provider'
import Navbar from '@/components/Navbar'

export const metadata = {
	title: 'Mentor',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<div className='w-[90%] m-auto'>
						<Navbar />
						{children}
					</div>
				</Providers>
			</body>
		</html>
	)
}
