import Navbar from '@/components/navbar/Navbar'
import './globals.css'
// import { Providers } from './redux/provider'
import { Poppins } from 'next/font/google'

export const metadata = {
	title: 'Mentor',
	description: 'Generated by create next app',
}

const poppins = Poppins({
	weight: ['300', '400', '500', '600', '700'],
	display: 'swap',
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className={poppins.className}>
			<body>
				{/* <Providers> */}
				<Navbar />
				{children}
				{/* </Providers> */}
			</body>
		</html>
	)
}
